[[redirects]]
from = "/plants/family/:family/uuid/:uuid/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/plants/family/:family/genus/:genus/uuid/:uuid/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/plants/family/:family/genus/:genus/species/:species/variety/:variety/uuid/:uuid/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/plants/family/:family/genus/:genus/species/:species/uuid/:uuid/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/plants/common-names/:common/uuid/:uuid/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/nurseries/nursery/:nursery/uuid/:uuid/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
